### ISSUE TITLE
Dfunc and built-in models

### ISSUE THREAD

**Issue by Stuermer** [lmfit/lmfit-py#264]
What is the correct way / Is there a possibility to speed up fitting by using Dfun for built-in models? 
I was trying to pass Dfun as a fit_kws, but that didn't work with lmfit, but with scipy.leastsq directly.
See the attached code.

Would it be a good idea to implement Dfun for all built-in models and use it by default?

```python
import numpy as np
from scipy.optimize import leastsq
import matplotlib.pyplot as plt
from lmfit.models import GaussianModel

def f(var, x):
    return (var[0]/(np.sqrt(2.*np.pi)*var[2]))*np.exp(-(x-var[1])**2/(2.*var[2]**2))

def errfunc(var, x, y):
    return f(var,x) - y

def dfunc(var,x,y):
    fac = np.exp(-(x-var[1])**2/(2*var[2]**2))
    da = fac / (np.sqrt(2.*np.pi)* var[2])
    ds = var[0] * fac * ((x-var[1])**2-var[2]**2)/(np.sqrt(2.*np.pi)*var[2]**4)
    dmu= var[0]*fac * (x-var[1]) / (np.sqrt(2.*np.pi)*var[2]**3)
    return [da,dmu,ds]

xs = np.linspace(-4,4,1000)
ys = f([2.5,0,0.5],xs)
yn = ys + 0.2*np.random.normal(size=len(xs))


p1, C, info, msg, success  = leastsq(errfunc, [5,-1,3], args=(xs,yn), Dfun=dfunc, col_deriv=1, full_output=1)
print 'coded dfunc:******************'
print 'number of function calls: ', info['nfev']
print 'params', p1

p1, C, info, msg, success  = leastsq(errfunc, [5,-1,3], args=(xs,yn), full_output=1)
print 'no dfunc:*********************'
print 'number of function calls: ', info['nfev']
print 'params', p1

mod = GaussianModel()
pars = mod.make_params()
pars['center'].set(-1)
pars['sigma'].set(3)
pars['amplitude'].set(5)
out  = mod.fit(yn, pars, x=xs )
print 'lmfit without dfunc***********'
print 'number of function calls: ', out.nfev
print 'params', out.best_values

mod2 = GaussianModel()
pars2 = mod2.make_params()
pars2['center'].set(-1)
pars2['sigma'].set(3)
pars2['amplitude'].set(5)
out2  = mod2.fit(yn, pars,  x=xs, fit_kws={'Dfun': dfunc, 'col_deriv': 1})
print 'lmfit with dfunc**************'
print 'number of function calls: ', out2.nfev
print 'params', out2.best_values

out.plot()
plt.show()
```
ends with
```
coded dfunc:******************
number of function calls:  11
params [ 2.45953944  0.00476926  0.50025611]
no dfunc:*********************
number of function calls:  35
params [ 2.45953944  0.00476926  0.50025611]
lmfit without dfunc***********
number of function calls:  37
params {'sigma': 0.5002562634131544, 'center': 0.004769139615889575, 'amplitude': 2.459539827958798}
Traceback (most recent call last):
  File "/home/julian/.PyCharm40/config/scratches/scratch_4", line 49, in <module>
    out2  = mod2.fit(yn, pars2,  x=xs, fit_kws={'Dfun': dfunc, 'col_deriv': 1})
  File "/usr/local/lib/python2.7/dist-packages/lmfit/model.py", line 560, in fit
    output.fit(data=data, weights=weights)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/model.py", line 763, in fit
    _ret = self.minimize(method=self.method)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/minimizer.py", line 705, in minimize
    return function(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/minimizer.py", line 546, in leastsq
    lsout = scipy_leastsq(self.__residual, vars, **lskws)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/minpack.py", line 384, in leastsq
    _check_func('leastsq', 'Dfun', Dfun, x0, args, n, (n, m))
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/minpack.py", line 20, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/usr/local/lib/python2.7/dist-packages/lmfit/minimizer.py", line 284, in __jacobian
    jac = self.jacfcn(pars, *self.userargs, **self.userkws)
TypeError: dfunc() got multiple values for keyword argument 'x'
```
When I refactor 
```python
def dfunc(var,x,y):
...
```
to 
```python
def dfunc(var,xx,yy):
...
```
I get a different error message:
```
Traceback (most recent call last):
  File "/home/julian/.PyCharm40/config/scratches/scratch_4", line 50, in <module>
    out2  = mod2.fit(yn, pars2,  x=xs, fit_kws={'Dfun': dfunc, 'col_deriv': 1})
  File "/usr/local/lib/python2.7/dist-packages/lmfit/model.py", line 560, in fit
    output.fit(data=data, weights=weights)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/model.py", line 763, in fit
    _ret = self.minimize(method=self.method)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/minimizer.py", line 705, in minimize
    return function(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/minimizer.py", line 546, in leastsq
    lsout = scipy_leastsq(self.__residual, vars, **lskws)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/minpack.py", line 384, in leastsq
    _check_func('leastsq', 'Dfun', Dfun, x0, args, n, (n, m))
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/minpack.py", line 20, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/usr/local/lib/python2.7/dist-packages/lmfit/minimizer.py", line 284, in __jacobian
    jac = self.jacfcn(pars, *self.userargs, **self.userkws)
TypeError: dfunc() got an unexpected keyword argument 'x'
```
Any help is appreciated.

**Comment by newville** [comment]
@Stuermer  Well, you can certainly use `Minimizer` with an analytic Jacobian.  But the call signature of the Jacobian and residual have to match (that is: first arguments is a Parameters object), and the elements of the returned Jacobian array have to be ordered (same order as the truly variable Parameters).

Using analytic Jacobian with a built-in model would require that you know a lot about the residual function.

**Comment by Stuermer** [comment]
@newville Thanks. I was able to fix the code. I attached a minimal working example. 
I have two remaining questions:
1. Is it save to hardcode the oder of the parameters ? Or can any of the internal lmfit function change the order of the elements ? 
2. From your last comment I infer that there are cases where it is disadvantageous (or even wrong?) to provide dfunc?

```python
import numpy as np
import matplotlib
matplotlib.use('Qt4Agg')
import matplotlib.pyplot as plt

from lmfit.models import GaussianModel
from lmfit.lineshapes import gaussian

def dfunc_gaussian(params,*ys,**xs):
    xx = xs['x']
    var = params.valuesdict()
    fac = np.exp(-(xx-var['center'])**2/(2.*var['sigma']**2))
    da = fac / (np.sqrt(2.*np.pi)* var['sigma'])
    ds = var['amplitude'] * fac * ((xx-var['center'])**2-var['sigma']**2)/(np.sqrt(2.*np.pi)*var['sigma']**4)
    dmu= var['amplitude']*fac * (xx-var['center']) / (np.sqrt(2.*np.pi)*var['sigma']**3)
    return np.array([ds,dmu,da])

xs = np.linspace(-4,4,1000)
ys = gaussian(xs, 2.5,0,0.5)
yn = ys + 0.2*np.random.normal(size=len(xs))

mod = GaussianModel()
pars = mod.guess(yn,xs)
out  = mod.fit(yn, pars, x=xs )
out2 = mod.fit(yn, pars,  x=xs, fit_kws={'Dfun': dfunc_gaussian, 'col_deriv': 1})
print 'lmfit without dfunc***********'
print 'number of function calls: ', out.nfev
print 'params', out.best_values
print 'lmfit with dfunc**************'
print 'number of function calls: ', out2.nfev
print 'params', out2.best_values
out2.plot(datafmt='.')
plt.show()
```
gives
```
lmfit without dfunc***********
number of function calls:  23
params {'sigma': 0.4879645236841226, 'center': -0.00340724041091985, 'amplitude': 2.4853915712025825}
lmfit with dfunc**************
number of function calls:  14
params {'sigma': 0.4879645238679491, 'center': -0.003407236577842011, 'amplitude': 2.4853915717699464}
```

![figure_1](https://cloud.githubusercontent.com/assets/6728233/10397309/9598ab82-6e6c-11e5-82a9-ef95610c65c8.png)

**Comment by newville** [comment]
@Stuermer   Thanks for the very nice example.  Maybe we can include this as an example?

> I have two remaining questions:
>  1. Is it save to hardcode the oder of the parameters ? Or can any of the internal lmfit
>  functions change the order of the elements ?

Yes. Parameters are ordered (derives from OrderedDict, so ordered by insertion), and you can rely on that.  However, any Parameter can be fixed (`vary=False`), and the `Minimize` class keeps this information so that it can map the Parameter values into the array of variable parameters really needed for the scipy.optimize codes.  I think the Jacobian needs to return the array of derivatives for the variable parameters, so if you fix parameters, I think you need to alter the Jacobian function.

> 2. From your last comment I infer that there are cases where it is disadvantageous 
> (or even wrong?) to provide dfunc?

I wouldn't say "wrong", but to provide dfunc, you sort of have to know func (the objective function) in some detail.  And part of the point of "Model" is that the user thinks about the "model function", not the objective function.   So, I'd say that it seems more natural to me to use Minimizer for a problem where you are using an analytic Jacobian.

**Comment by Stuermer** [comment]
I triggered a pull request with a slightly extended example. Feel free to include it.

> I wouldn't say "wrong", but to provide dfunc, you sort of have to know func (the objective function) in some detail. And part of the point of "Model" is that the user thinks about the "model function", not the objective function. So, I'd say that it seems more natural to me to use Minimizer for a problem where you are using an analytic Jacobian.

Ok I see. However, what I ment was maybe it would be a good idea to provide the dfunc for some/all built-in models. The user wouldn't notice when he uses the Model.fit() that 'internally' the analytic dfunc is used. 

Saying that, I found that it seems that it is not always 'better' to provide the jacobian. I attached another example file (basically the same as the example as above, but for different lineshapes).
For Gaussian, Lorentzian and Moffat shapes, providing the analytic dfunc clearly improves the needed number of evaluations. For the Voigt and the PseudoVoigt it seems there is no advantage - to the contrary, .nfev is even increasing (for most random realizations). I don't really understand why. I suspect it is either some numerical issue within dfunc or it has to do with the way leastsq determines the stepsize in case dfunc is provided. Unfortunately the documentation of scipys leastsq isn't very helpful here.

```python
__author__ = 'stuermer'
import matplotlib
matplotlib.use('Qt4Agg')
import matplotlib.pyplot as plt
from lmfit.models import *
from lmfit.lineshapes import  *

def moffat(x, amplitude=1, center=0., sigma=1, beta=1.):
    return amplitude / (((x - center)/sigma)**2 + 1)**beta

class MoffatModel(Model):
    __doc__ = gaussian.__doc__ + COMMON_DOC if gaussian.__doc__ else ""
    def __init__(self, *args, **kwargs):
        super(MoffatModel, self).__init__(moffat, *args, **kwargs)

    def guess(self, data, x=None, negative=False, **kwargs):
        pars = guess_from_peak(self, data, x, negative, ampscale = 0.25)
        return update_param_vals(pars, self.prefix, **kwargs)

def dfunc_moffat(params, *ys, **xs):
    xx = xs['x']
    var = params.valuesdict()
    A = var['amplitude']
    da = (1./(1. + (xx - var['center'])**2/var['sigma']**2))**var['beta']
    dmu = (2.*A*var['beta']*(xx - var['center'])*(1./(1. + (xx - var['center'])**2/var['sigma']**2))**(1. + var['beta']))/var['sigma']**2
    db = A*(1./(1. + (xx - var['center'])**2/var['sigma']**2))**var['beta']*np.log(1./(1 + (xx - var['center'])**2/var['sigma']**2))
    ds= (2.*A*var['beta']*(xx - var['center'])**2*(1/(1 + (xx - var['center'])**2/var['sigma']**2))**(1. + var['beta']))/var['sigma']**3
    return np.array([db,ds,dmu,da])

def dfunc_gaussian(params,*ys,**xs):
    xx = xs['x']
    var = params.valuesdict()
    fac = np.exp(-(xx-var['center'])**2/(2.*var['sigma']**2))
    da = fac / (s2pi* var['sigma'])
    ds = var['amplitude'] * fac * ((xx-var['center'])**2-var['sigma']**2)/(s2pi*var['sigma']**4)
    dmu= var['amplitude']*fac * (xx-var['center']) / (s2pi*var['sigma']**3)
    return np.array([ds,dmu,da])

def dfunc_lorentzian(params, *ys, **xs):
    xx = xs['x']
    var = params.valuesdict()
    fac = ((xx-var['center'])**2+var['sigma']**2)
    ds = (var['amplitude']*((xx-var['center'])**2-var['sigma']**2))/ (pi*fac**2)
    da = var['sigma'] /(pi*fac)
    dmu= (2.*var['amplitude']*(xx-var['center'])*var['sigma'])/(pi*fac**2)
    return np.array([ds,dmu,da])

def dfunc_voigt(params, *ys, **xs):
    xx = xs['x']
    var = params.valuesdict()
    z = (xx-var['center']+1j*var['gamma']) / (var['sigma']*s2)

    da = wofz(z).real / (s2pi*var['sigma'])
    ds = 1. / (s2pi*var['sigma']**2)* var['amplitude'] *\
         (np.sqrt(2./pi)*var['sigma']*((xx-var['center']+1j*var['gamma'])/var['sigma']**2).imag
          + var['sigma']*(wofz(z)*(xx-var['center']+1j*var['gamma'])**2/var['sigma']**3).real
          - wofz(z).real )
    dg = 0.
    dmu = var['amplitude']/(s2pi*var['sigma']) * (wofz(z)*(xx-var['center']+1j*var['gamma'])/ var['sigma']**2).real +\
          var['amplitude']*(1./var['sigma']).imag/(pi*var['sigma'])

    return np.array([da, ds, dmu])


def dfunc_pseudovoigt(params, *ys, **xs):
    xx = xs['x']
    var = params.valuesdict()
    A = var['amplitude']
    a = var['fraction']
    s = var['sigma']
    mu = var['center']
    dA = -((-1 + a)/(np.exp((mu - xx)**2/(2.*s**2))*np.sqrt(2*pi)*s)) + (a*s)/(pi*(s**2 + (mu - xx)**2))
    # dA = (a*s)/(pi*((xx - mu)**2 + s**2)) - ((-1. + a)*np.sqrt(log2/pi))/(2**((xx - mu)**2/s**2)*s)
    ds = ((-1 + a)*A)/(np.exp((mu - xx)**2/(2.*s**2))*np.sqrt(2*pi)*s**2) - (2*a*A*s**2)/(pi*(s**2 + (mu - xx)**2)**2) + (a*A)/(pi*(s**2 + (mu - xx)**2)) \
         -  ((-1 + a)*A*(mu - xx)**2)/(np.exp((mu - xx)**2/(2.*s**2))*np.sqrt(2*pi)*s**4)

    dmu =  ((-1 + a)*A*(mu - xx))/(np.exp((mu - xx)**2/(2.*s**2))*np.sqrt(2*pi)*s**3) + (2*a*A*s*(-mu + xx))/(pi*(s**2 + (mu - xx)**2)**2)
    da = A*(-(1/(np.exp((mu - xx)**2/(2.*s**2))*np.sqrt(2*pi)*s)) + s/(pi*(s**2 + (mu - xx)**2)))

    return np.array([dA, ds, dmu, da])


if __name__ == '__main__':
    print '**********************************'
    print '***** Test Moffat ***************'
    print '**********************************'
    xs = np.linspace(-4, 4, 100)
    ys = moffat(xs, 2.5, 0, 0.5, 1.)
    yn = ys + 0.1*np.random.normal(size=len(xs))

    mod = MoffatModel()
    pars = mod.guess(yn, xs)
    out  = mod.fit(yn, pars, x=xs)

    out2 = mod.fit(yn, pars,  x=xs, fit_kws={'Dfun': dfunc_moffat, 'col_deriv': 1, 'xtol':1E-6})
    # out2  = mod.fit(yn, pars, x=xs )
    print 'lmfit without dfunc **************'
    print 'number of function calls: ', out.nfev
    print 'params', out.best_values
    print 'lmfit with dfunc *****************'
    print 'number of function calls: ', out2.nfev
    print 'params', out2.best_values
    print '\n \n'
    out.plot(datafmt='.')


    print '**********************************'
    print '***** Test Gaussian **************'
    print '**********************************'
    xs = np.linspace(-4, 4, 100)
    ys = gaussian(xs, 2.5,0,0.5)
    yn = ys + 0.1*np.random.normal(size=len(xs))

    mod = GaussianModel()
    pars = mod.guess(yn, xs)
    out  = mod.fit(yn, pars, x=xs )
    out2 = mod.fit(yn, pars,  x=xs, fit_kws={'Dfun': dfunc_gaussian, 'col_deriv': 1})
    print 'lmfit without dfunc **************'
    print 'number of function calls: ', out.nfev
    print 'params', out.best_values
    print 'lmfit with dfunc *****************'
    print 'number of function calls: ', out2.nfev
    print 'params', out2.best_values
    print '\n \n'
    out2.plot(datafmt='.')


    print '**********************************'
    print '***** Test Lorentzian ************'
    print '**********************************'
    xs = np.linspace(-4,4,100)
    ys = lorentzian(xs, 2.5,0,0.5)
    yn = ys + 0.1*np.random.normal(size=len(xs))

    mod = LorentzianModel()
    pars = mod.guess(yn, xs)
    out  = mod.fit(yn, pars, x=xs )
    out2 = mod.fit(yn, pars,  x=xs, fit_kws={'Dfun': dfunc_lorentzian, 'col_deriv': 1})
    print 'lmfit without dfunc **************'
    print 'number of function calls: ', out.nfev
    print 'params', out.best_values
    print 'lmfit with dfunc *****************'
    print 'number of function calls: ', out2.nfev
    print 'params', out2.best_values
    print '\n \n'
    out2.plot(datafmt='.')


    print '**********************************'
    print '***** Test Voigt *****************'
    print '**********************************'
    xs = np.linspace(-4, 4, 100)
    ys = voigt(xs, 2.5, 0, 0.5)
    yn = ys + 0.1*np.random.normal(size=len(xs))

    mod = VoigtModel()
    pars = mod.guess(yn, xs)
    out  = mod.fit(yn, pars, x=xs )
    out2 = mod.fit(yn, pars,  x=xs, fit_kws={'Dfun': dfunc_voigt, 'col_deriv': 1})
    print 'lmfit without dfunc **************'
    print 'number of function calls: ', out.nfev
    print 'params', out.best_values
    print 'lmfit with dfunc *****************'
    print 'number of function calls: ', out2.nfev
    print 'params', out2.best_values
    print '\n \n'
    out2.plot(datafmt='.')


    print '**********************************'
    print '***** Test PseudoVoigt ***********'
    print '**********************************'
    xs = np.linspace(-4,4,100)
    ys = pvoigt(xs, 2.5,0,0.5,0.3)
    yn = ys + 0.1*np.random.normal(size=len(xs))

    mod = PseudoVoigtModel()
    pars = mod.guess(yn, xs)
    out  = mod.fit(yn, pars, x=xs )
    out2 = mod.fit(yn, pars,  x=xs, fit_kws={'Dfun': dfunc_pseudovoigt, 'col_deriv': 1})
    print 'lmfit without dfunc **************'
    print 'number of function calls: ', out.nfev
    print 'params', out.best_values
    print 'lmfit with dfunc *****************'
    print 'number of function calls: ', out2.nfev
    print 'params', out2.best_values
    out2.plot(datafmt='.')


    plt.show()
```

**Comment by newville** [comment]
@Stuermer As an example to include in the docs, I think #268 is great.   I'll wait just to give others a chance to comment, but think it should be merged soon.

For automatically using analytic derivatives:  I believe this would prevent one from "fixing" parameter values or complex constraints, at least at the moment.  It's also not clear how to handle Composite Models (say, GaussianModel + GaussianModel + QaudraticModel).   Both of these are probably doable, but I'm not sure it's worth the complexity.

**Comment by Stuermer** [comment]
@newville I agree, it would require quite some effort to implement dfuncs for inbuilt-models especially taking fixed parameters and Composite Models into account. Additive models should still be easier - as I guess the jacobians are also additive; but more complex models will need more effort.

Just as a sidenote: While I was trying to speed up the least square fit I stumbled across a library called AlgoPy that allows the effective calculation of derivatives of functions, and which can also be used to improve leastsquare fitting.
<https://pythonhosted.org/algopy/examples/leastsquaresfitting.html>

From my side the issue can be closed, the code is now working... To implmenet dfuncs for inbuilt models was just thought.
