### ISSUE TITLE
sigma parameter not defined for PseudoVoigtModel (lmfit 0.9.2)

### ISSUE THREAD

**Issue by feranick** [lmfit/lmfit-py#312]
Starting with lmfit version 0.9, I encountered an issue the is not present in previous 0.8.4. To illustrate the difference, I run the following code on a set of data with the two versions:

```
    peakA = PseudoVoigtModel(prefix="pA"+ str(i) +"_")
    peakB = PseudoVoigtModel(prefix="pB"+ str(i) +"_")

    pars = peakA.guess(y, x=x)
    pars += peakB.guess(y, x=x)
    print(pars)
```
This error is only present for the PseudoVoigtModel. No issues with other models regardless of the version (lmfit). 

**Output lmfit 0.8.4:**

`Parameters([('pA8_sigma', <Parameter 'pA8_sigma', 125.877765, bounds=[0.0:inf]>), ('pA8_gamma', <Parameter 'pA8_gamma', 125.877765, bounds=[-inf:inf], expr='pA8_sigma'>), ('pA8_fwhm', <Parameter 'pA8_fwhm', 453.32485387214996, bounds=[-inf:inf], expr='3.6013100*pA8_sigma'>), ('pA8_amplitude', <Parameter 'pA8_amplitude', 84840.736464103786, bounds=[-inf:inf]>), ('pA8_center', <Parameter 'pA8_center', 1391.8472744394619, bounds=[-inf:inf]>), ('pB8_sigma', <Parameter 'pB8_sigma', 125.877765, bounds=[0.0:inf]>), ('pB8_gamma', <Parameter 'pB8_gamma', 125.877765, bounds=[-inf:inf], expr='pB8_sigma'>), ('pB8_fwhm', <Parameter 'pB8_fwhm', 453.32485387214996, bounds=[-inf:inf], expr='3.6013100*pB8_sigma'>), ('pB8_amplitude', <Parameter 'pB8_amplitude', 84840.736464103786, bounds=[-inf:inf]>), ('pB8_center', <Parameter 'pB8_center', 1391.8472744394619, bounds=[-inf:inf]>)])
`

**Output lmfit 0.9.2:**

```
NameError
   <_ast.Module object at 0x7f6783aa6a50>
              ^^^
name 'pB8_sigma' is not defined
Traceback (most recent call last):
  File "./multifit_exp_20160305.py", line 831, in <module>
    sys.exit(main())
  File "./multifit_exp_20160305.py", line 381, in main
    calculate(rs.x, rs.y, '0', '0', file, type, False, True, '')
  File "./multifit_exp_20160305.py", line 110, in calculate
    pars += peakB.guess(y, x=x)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/parameter.py", line 103, in __iadd__
    self.add_many(*params)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/parameter.py", line 231, in add_many
    self.__setitem__(para.name, para)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/parameter.py", line 85, in __setitem__
    self._asteval.symtable[key] = par.value
  File "/usr/local/lib/python2.7/dist-packages/lmfit/parameter.py", line 559, in value
    return self._getval()
  File "/usr/local/lib/python2.7/dist-packages/lmfit/parameter.py", line 535, in _getval
    check_ast_errors(self._expr_eval)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/parameter.py", line 22, in check_ast_errors
    expr_eval.raise_exception(None)
  File "/usr/local/lib/python2.7/dist-packages/lmfit/asteval.py", line 167, in raise_exception
    raise exc(self.error_msg)
```

**Comment by newville** [comment]
@feranick  You're right -- somehow `sigma` got removed from PseudoVoigtModel.  It's an easy fix.
