### ISSUE TITLE
ValueError when using scipy development version

### ISSUE THREAD

**Issue by benmaier** [lmfit/lmfit-py#497]
# Description

When a `scipy` development version is installed, determining its version fails in lmfit/minimizer.py

```python
major, minor, micro = np.array(scipy_version.split('.'), dtype='int')
```

Generates the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bfmaier/.local/lib/python3.6/site-packages/lmfit/__init__.py", line 42, in <module>
    from .confidence import conf_interval, conf_interval2d
  File "/home/bfmaier/.local/lib/python3.6/site-packages/lmfit/confidence.py", line 12, in <module>
    from .minimizer import MinimizerException
  File "/home/bfmaier/.local/lib/python3.6/site-packages/lmfit/minimizer.py", line 134, in <module>
    major, minor, micro = np.array(scipy_version.split('.'), dtype='int')
ValueError: invalid literal for int() with base 10: 'dev0+dfb0cc2'
```

# Versions

* lmfit: 0.9.11
* scipy: 1.2.0.dev0+dfb0cc2

# Minimal example

This works only when a scipy dev version is installed.

```python
import lmfit
```

**Comment by benmaier** [comment]
suggested solution:

replace both occurences of

```python
major, minor, micro = np.array(scipy_version.split('.'), dtype='int')
```

in `minimizer.py` with

```python
major, minor, micro = np.array((scipy_version.split('.dev')[0]).split('.'), dtype='int')
```
