### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by geom16011** [lmfit/lmfit-py#517]
Installed properly the package. 

But when i do import lmfit i get the following error: 

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import lmfit
  File "C:\Python27\lib\site-packages\lmfit\__init__.py", line 42, in <module>
    from .confidence import conf_interval, conf_interval2d
  File "C:\Python27\lib\site-packages\lmfit\confidence.py", line 12, in <module>
    from .minimizer import MinimizerException
  File "C:\Python27\lib\site-packages\lmfit\minimizer.py", line 133, in <module>
    major, minor, micro = np.array(scipy_version.split('.'), dtype='int')
ValueError: invalid literal for long() with base 10: '0rc1'

Any ideas?

**Comment by newville** [comment]
@geom16011 fixed in github master branch, we're hoping for a release of 0.9.12 very soon.
