### ISSUE TITLE
Error when adding two Parameters objects with certain constraint expressions

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#560]
`Parameters` objects are meant to support addition or joining with `+`.  This can fail when constraint expressions are involved.  See https://groups.google.com/forum/#!topic/lmfit-py/W9Fqhqbx7e8

###### A Minimal, Complete, and Verifiable example

```python 
import lmfit
params1 = lmfit.Parameters()
params1.add("a", value=1.0)

params2 = lmfit.Parameters()
params2.add("b", value=1.0)
params2.add("c", value=2.0)
params2['b'].expr = 'c/2'

params = params1 + params2
```

###### Error message:

The above code with raise
```
NameError
   <_ast.Module object at 0x10b27b198>
name 'c' is not defined
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 140, in __add__
    out.add_many(*params)
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 392, in add_many
    self.__setitem__(para.name, para)
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 132, in __setitem__
    self._asteval.symtable[key] = par.value
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 819, in value
    return self._getval()
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 801, in _getval
    check_ast_errors(self._expr_eval)
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 25, in check_ast_errors
    expr_eval.raise_exception(None)
  File "/Users/Newville/anaconda3/lib/python3.7/site-packages/asteval-0.9.14-py3.7.egg/asteval/asteval.py", line 261, in raise_exception
NameError: at expr='<_ast.Module object at 0x10b27b198>'
```

The basic problem here is that `params2` is now "out of order" and looping through the entries in `params2` to add to `params1` would effectively be doing
 
```
params.add('b', expr='c/2')
```
*before* `c` was defined in `params`.

**Comment by reneeotten** [comment]
Fixed with the merge of PR#561 in commit aa0510e5aa0b90baacdfbc16f1b1e7216eac243f
