### ISSUE TITLE
emcee method not recoginzed?

### ISSUE THREAD

**Issue by mfWeeWee** [lmfit/lmfit-py#563]
```
from scipy.integrate import odeint
import numpy as np
from lmfit import Minimizer, Parameters, report_fit, minimize
from matplotlib.pyplot import figure, plot, scatter
time = 10
Nt = 10
tt = np.linspace(0,time, Nt)

from SALib.sample import saltelli
from SALib.analyze import sobol
import numpy as np
from sys import exit

x0 = np.array([1,0.5,0,0,0])

def f(xs, t, ps):
    """Test"""
    try:
        k1 = ps['k1'].value
        k2 = ps['k2'].value
        k3 = ps['k3'].value
        k4 = ps['k4'].value
    except:
        k1, k2, k3, k4 = ps

    a, a1, b, c, d = xs
    return [-k1*a,-k2*a1, k1*a + k2*a1, k3*b, k4*b]

def g(t, x0, ps):
    """
    Solution to the ODE x'(t) = f(t,x,k) with initial condition x(0) = x0
    """
    x = odeint(f, x0, t, args=(ps,))
    return x

def residual(ps, ts, data):
    x0 = ps['a'].value, ps['a1'].value, ps['b'].value, ps['c'].value, ps['d'].value
    model = g(ts, x0, ps)
    return (model - data).ravel()

#t = np.linspace(0, 10, 100)
x0 = np.array([1,0.5,0,0,0])

k1, k2, k3, k4 = 1,0.8,0.7,0.2
true_params = np.array((k1,k2,k3,k4))
data = g(tt, x0, true_params)

data += (np.random.normal(size=data.shape))
lb, ub = 0.2, 0.2

# set parameters incluing bounds
params = Parameters()
params.add('a', value = x0[0] , min=0, max=1.5)
params.add('a1', value = x0[1], min=0, max=2.5)
params.add('b', value = x0[2], min=0, max=1)
params.add('c', value= x0[3] , min=0, max=1)
params.add('d', value= x0[4] , min=0, max=1)
params.add('k1', value=k1, min=k1 - lb, max=k1 + ub)
params.add('k2', value=k2, min=k2 - lb, max=k2 + ub)
params.add('k3', value=k3, min=k3 - lb, max=k3 + ub)
params.add('k4', value=k4, min=k4 - lb, max=k4 + ub)

# fit model and find predicted values
result = minimize(residual, params, args=(tt, data), method='emcee')
#result = Minimizer.emcee(params)
final = data + result.residual.reshape(data.shape)

# plot data and fitted curves
figure(1)
plot(tt, data, 'o')
plot(tt, final, '-', linewidth=2);

# display fitted statistics
report_fit(result)

problem = {
    'num_vars': 4,
    'names': ['k1', 'k2', 'k3', 'k4'],
    'bounds': [[(result.params['k1'].value) - 0.02, (result.params['k1'].value) + 0.02],
               [(result.params['k2'].value) - 0.02, (result.params['k2'].value) + 0.02],
               [(result.params['k3'].value) - 0.02, (result.params['k3'].value) + 0.02],
               [(result.params['k4'].value) - 0.02, (result.params['k4'].value) + 0.02]]
}
param_values = saltelli.sample(problem, 100 , calc_second_order=True)

A = (param_values).T
#print (A[0])
#print (A[2])
figure(2)
for i in range(100):
    scatter(A[0],A[2])
N = len(param_values) # number of parameter samples
Y = np.zeros([param_values.shape[0]])
#print(len(param_values[0]))

Y = []
for i in range(N):
    Y.append((g(tt,x0,(param_values[i]))))
b = np.vstack(Y)
a = np.concatenate(Y, axis=None)
figure(3)
for i in range(10):
    plot(tt,final)
    plot(tt, Y[i])

Si = sobol.analyze(problem, a, print_to_console=False)
print (Si['S1'])
print (Si['ST'])
#
```
Traceback error: 
```
Traceback (most recent call last):

  File "<ipython-input-78-2832f44257d4>", line 1, in <module>
    runfile(lmfit+SALib.py', wdir=/folder')

  File "/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/lmfit+SALib.py", line 64, in <module>
    result = minimize(residual, params, args=(tt, data), method='emcee')

  File "/anaconda3/lib/python3.7/site-packages/lmfit/minimizer.py", line 2300, in minimize
    return fitter.minimize(method=method)

  File "/anaconda3/lib/python3.7/site-packages/lmfit/minimizer.py", line 1949, in minimize
    return function(**kwargs)

  File "/anaconda3/lib/python3.7/site-packages/lmfit/minimizer.py", line 1141, in emcee
    raise NotImplementedError('You must have emcee to use'

NotImplementedError: You must have emcee to use the emcee method
```
I don't understand? DO i need to install the emcee thing separately?

**Comment by reneeotten** [comment]
Yes, as is described in [the manual](https://lmfit.github.io/lmfit-py/installation.html). Also, for the future, please read and follow the instructions before opening an Issue, this is clearly something that belongs on the mailinglist not on GitHub.
